version: "3"

services:
  prisma-test:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prisma
      MYSQL_USER: prisma
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
    hostname: prisma-test
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d